# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efa0b5c98d7cc47cecdc043c506b0231e8234d319ce9c4e5a9bcd97c68fc679da3b01c519fba99d98f67d77aaec1c15f441e5c9713c63944f37c754f9ca43192

test:
  secret_key_base: 80287ae6400092b892ba495492f0c1ed375eb788016e674e8c282b74b1b4f1294b16036d52f0fe4f22b24667af274cdc2ca0ba8db49b34eb781f031a5d847c40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
